#ifndef __KLITE_CFG_H
#define __KLITE_CFG_H

#include "modules.h"

#if KLITE_CFG_MLFQ
#define KLITE_CFG_ROUND_ROBIN 1
#define KLITE_CFG_ROUND_ROBIN_SLICE 1
#define KLITE_CFG_MAX_PRIO KLITE_CFG_MLFQ_LEVEL_NUM
#define KLITE_CFG_ROUND_ROBIN_SLICE_DEFAULT KLITE_CFG_MLFQ_RR_TICK
#endif

#endif /* KLITE_CFG_H */
